name: Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Disable AppArmor for Puppeteer
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Start local server
        run: npm run preview &

      - name: Generate worksheets
        run: npm run generate

      - name: Set Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short=12 HEAD)" >> $GITHUB_OUTPUT

      - name: Create tarball
        run: tar -czf worksheets.tar.gz -C out .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('preview-{0}', steps.vars.outputs.sha_short) }}
          release_name: ${{ startsWith(github.ref, 'refs/tags/') && format('Release {0}', github.ref_name) || format('Preview {0}', steps.vars.outputs.sha_short) }}
          body: |
            Worksheet release.
          draft: false
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}

      - name: Upload Worksheet Tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./worksheets.tar.gz
          asset_name: worksheets.tar.gz
          asset_content_type: application/gzip

      - name: Clean up older pre-releases
        uses: sgpublic/delete-release-action@v1.1
        with:
          pre-release-drop: true
          pre-release-keep-count: 3
          pre-release-drop-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
